---
name: Build Docker image
on:
  push:
    branches:
       - '**'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup Docker cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::144363388242:role/github-actions
          role-session-name: demo-php-5.6

      - name: Login to AWS ECR
        uses: docker/login-action@v2
        with:
          registry: 144363388242.dkr.ecr.us-west-2.amazonaws.com

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}
      
      - name: Create image metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/joberly/demo-php-5.6
            144363388242.dkr.ecr.us-west-2.amazonaws.com/demo-php-5.6
          tags: |
            type=sha,prefix=
            type=sha,format=long,prefix=

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          platforms: 'linux/amd64'
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          build-args: |
            DEMO_COMMIT=${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
